.TH ft_pow 3 "29 April 2019" "version 1.0"
.SH NAME
.BR ft_pow ", " ft_lpow ", " ft_llpow ", " ft_ullpow " -- power function"
.SH LIBRARY
42 C Library (libft, -lft)
.SH SYNOPSIS
.B #include \(dqft_math.h\(dq
.PP
\fIlong double\fR
.br
\fBft_pow\fR(\fIlong double base\fR, \fIlong double exp\fR);
.PP
\fIlong\fR
.br
\fBft_lpow\fR(\fIint base\fR, \fIint exp\fR);
.PP
\fIlong long\fR
.br
\fBft_llpow\fR(\fIint base\fR, \fIint exp\fR);
.PP
\fIunsigned long long\fR
.br
\fBft_ullpow\fR(\fIint base\fR, \fIint exp\fR);
.SH DESCRIPTION
The \fBft_pow\fR() functions compute \fIbase\fR raised to the power \fIexp\fR.
.SH BUGS
No known bugs.
.SH AUTHOR
Written by Phillip Heilbron.
