.TH ft_printf 3 "29 April 2019" "version 1.0"
.SH NAME
.BR ft_printf ", " ft_sprintf ", " ft_nsprintf ", " ft_fprintf " -- formatted"
.br
output conversion
.SH LIBRARY
42 C Library (libft, -lft)
.SH SYNOPSIS
.B #include \(dqft_stdio.h\(dq
.PP
\fIint\fR
.br
\fBft_printf\fR(\fIconst char *format\fR, \fI...\fR);
.PP
\fIint\fR
.br
\fBft_sprintf\fR(\fIchar *str\fR, \fIconst char *format\fR, \fI...\fR);
.PP
\fIint\fR
.br
\fBft_nsprintf\fR(\fIchar *str\fR, \fIconst char *format\fR, \fI...\fR);
.PP
\fIint\fR
.br
\fBft_fprintf\fR(\fIint fd\fR, \fIconst char *format\fR, \fI...\fR);
.SH DESCRIPTION
The \fBft_pow\fR() functions compute \fIbase\fR raised to the power \fIexp\fR.
.SH BUGS
No known bugs.
.SH AUTHOR
Written by Phillip Heilbron.
